- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '10.2 SN.2 Remove Support for Internet Services (inetd)'
      shell: svcs -Ho state svc:/network/inetd
      register: inetd
      ignore_errors: true

    - name: inetd output
      debug: 
        msg: "{{ inetd.stdout }}"

    - name: 10.2 is compliant
      debug:
        msg: "10.2 is compliant"
      when: |
        inetd.stdout == "disabled"
      register: compliant

    - name: Compliant
      debug:
        msg: "10.2 is compliant"
      when: compliant.msg == "10.2 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "10.2 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        svcadm disable svc:/network/inetd
      when: isNonCompliant.msg == "10.2 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "10.2 is non-compliant"

    - name: FINAL
      debug:
        msg: "10.2 is compliant"
      when: isCompliant.msg == "10.2 is compliant"