- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '2.10 Disable Removeable Volume Manager'
      shell: |
        svcs -Ho state svc:/system/filesystem/rmvolmgr
      register: volmgr
      ignore_errors: true

    - name: '2.10 Disable Removeable Volume Manager'
      shell: |
        svcs -Ho state svc:/network/rpc/smserver
      register: smserver
      ignore_errors: true

    - name: server output
      debug: 
        msg: "{{ volmgr.stdout }}"

    - name: server output
      debug: 
        msg: "{{ smserver.stdout }}"

    - name: 2.10 is compliant
      debug:
        msg: "2.10 is compliant"
      when: 
        - (volmgr.stdout == "" or volmgr.stdout == "disabled")
        - (smserver.stdout == "" or smserver.stdout == "disabled")
      register: compliant

    - name: Compliant
      debug:
        msg: "2.10 is compliant"
      when: compliant.msg == "2.10 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "2.10 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        svcadm disable svc:/system/filesystem/rmvolmgr
        svcadm disable svc:/network/rpc/smserver
      when: isNonCompliant.msg == "2.10 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "2.10 is non-compliant"

    - name: FINAL
      debug:
        msg: "2.10 is compliant"
      when: isCompliant.msg == "2.10 is compliant"

    