- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '2.12 Disable Telnet Service'
      command: svcs -Ho state svc:/network/telnet
      register: telnet
      ignore_errors: true

    - name: telnet output
      debug: 
        msg: "{{ telnet.stdout }}"


    - name: 2.12 is compliant
      debug:
        msg: "2.12 is compliant"
      when: telnet.stdout == "" or telnet.stdout == "disabled"
      register: compliant

    - name: Compliant
      debug:
        msg: "2.12 is compliant"
      when: compliant.msg == "2.12 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "2.12 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        svcadm disable svc:/network/telnet
      when: isNonCompliant.msg == "2.12 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "2.12 is non-compliant"

    - name: FINAL
      debug:
        msg: "2.12 is compliant"
      when: isCompliant.msg == "2.12 is compliant"