- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '2.4 Disable RPC Encryption Key'
      shell: svcs -Ho state svc:/network/rpc/keyserv
      register: result
      ignore_errors: true

    - name: result output
      debug: 
        msg: "{{ result.stdout }}"

    - name: 2.4 is compliant
      debug:
        msg: "2.4 is compliant"
      when: result.stdout == "" or result.stdout == "disabled"
      register: compliant

    - name: Compliant
      debug:
        msg: "2.4 is compliant"
      when: compliant.msg == "2.4 is compliant"
      ignore_errors: true
      register: isCompliant
    
    - name: Non-Compliant
      debug:
        msg: "2.4 is non-compliant"
      when: compliant.skip_reason == "Conditional result was False"
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      command: svcadm disable svc:/network/rpc/keyserv
      when: isNonCompliant.msg == "2.4 is non-compliant"
    
    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "2.4 is non-compliant"
  
    - name: FINAL
      debug:
        msg: "2.4 is compliant"
      when: isCompliant.msg == "2.4 is compliant"
   

    