- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '3.16 Set Maximum Number of Imcoming Connections'
      command: ipadm show-prop -p _conn_req_max_q -co current tcp
      register: current
      ignore_errors: true

    - name: '3.16 Set Maximum Number of Imcoming Connections'
      command: ipadm show-prop -p _conn_req_max_q -co persistent tcp
      register: persistent
      ignore_errors: true

    - name: current output
      debug: 
        msg: "{{ current.stdout }}"

    - name: persistent output
      debug: 
        msg: "{{ persistent.stdout }}"

    - name: 3.16 is compliant
      debug:
        msg: "3.16 is compliant"
      when: current.stdout == "1024" and persistent.stdout == "1024"
      register: compliant

    - name: Compliant
      debug:
        msg: "3.16 is compliant"
      when: compliant.msg == "3.16 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "3.16 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        ipadm set-prop -p _conn_req_max_q=1024 tcp
      when: isNonCompliant.msg == "3.16 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "3.16 is non-compliant"

    - name: FINAL
      debug:
        msg: "3.16 is compliant"
      when: isCompliant.msg == "3.16 is compliant"