- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '3.5 Disable Soruce Packet Forwarding'
      command: ipadm show-prop -p _forward_src_routed -co current ipv4
      register: currentip
      ignore_errors: true

    - name: '3.5 Disable Soruce Packet Forwarding'
      command: ipadm show-prop -p _forward_src_routed -co persistent ipv4
      register: persistentip
      ignore_errors: true

    - name: current output
      debug: 
        msg: "{{ currentip.stdout }}"

    - name: persistent output
      debug: 
        msg: "{{ persistentip.stdout }}"

    - name: '3.5 Disable Soruce Packet Forwarding'
      command: ipadm show-prop -p _forward_src_routed -co current ipv6
      register: currentipv6
      ignore_errors: true

    - name: '3.5 Disable Soruce Packet Forwarding'
      command: ipadm show-prop -p _forward_src_routed -co persistent ipv6
      register: persistentipv6
      ignore_errors: true

    - name: current output
      debug: 
        msg: "{{ currentipv6.stdout }}"

    - name: persistent output
      debug: 
        msg: "{{ persistentipv6.stdout }}"

    - name: 3.5 is compliant
      debug:
        msg: "3.5 is compliant"
      when: 
        - (currentip.stdout == "0" and persistentip.stdout == "0")
        - (currentipv6.stdout == "0" and persistentipv6.stdout == "0")
      register: compliant

    - name: Compliant
      debug:
        msg: "3.5 is compliant"
      when: compliant.msg == "3.5 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "3.5 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        ipadm set-prop -p _forward_src_routed=0 ipv4;
        ipadm set-prop -p _forward_src_routed=0 ipv6;
      when: isNonCompliant.msg == "3.5 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "3.5 is non-compliant"

    - name: FINAL
      debug:
        msg: "3.5 is compliant"
      when: isCompliant.msg == "3.5 is compliant"
