- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '3.7 Enable Stack Protection'
      command: sxadm status -po extension,status,configuration nxheap,nxstack
      register: stack
      ignore_errors: true

    - name: stack output
      debug: 
        msg: "{{ stack.stdout }}"

    - name: 3.7 is compliant
      debug:
        msg: "3.7 is compliant"
      when: stack.stdout == "nxheap:enabled.tagged-files:default.default\nnxstack:enabled.all:default.default"
      register: compliant

    - name: Compliant
      debug:
        msg: "3.7 is compliant"
      when: compliant.msg == "3.7 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "3.7 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        sxadm delcust nxheap
        sxadm delcust nxstack
      when: isNonCompliant.msg == "3.7 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "3.7 is non-compliant"

    - name: FINAL
      debug:
        msg: "3.7 is compliant"
      when: isCompliant.msg == "3.7 is compliant"