- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '6.13 Disable X11 Forwarding for SSH'
      shell: grep "^X11Forwarding" /etc/ssh/sshd_config
      register: x11
      ignore_errors: true

    - name: x11 output
      debug: 
        msg: "{{ x11.stdout }}"

    - name: Compliant
      debug:
        msg: "6.13 is compliant"
      when: x11.stdout == "X11Forwarding yes"
      register: compliant
      ignore_errors: true

    - name: isCompliant
      debug:
        msg: "6.13 is compliant"
      when: compliant.msg == "6.13 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: isNotCompliant
      debug:
        msg: "6.13 is not compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        cp /etc/ssh/sshd_config /etc/ssh/sshd_config.orig;
        sed 's/^X11Forwarding no/X11Forwarding yes/' /etc/ssh/sshd_config > /etc/ssh/sshd_config.CIS;
        mv /etc/ssh/sshd_config.CIS /etc/ssh/sshd_config;
        svcadm restart svc:/network/ssh;
      when: isNonCompliant.msg == "6.13 is not compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "6.13 is not compliant"

    - name: FINAL
      debug:
        msg: "6.13 is compliant"
      when: isCompliant.msg == "6.13 is compliant"