- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '6.9 Disable root login for SSH'
      shell: grep "^PermitRootLogin" /etc/ssh/sshd_config
      register: ssh
      ignore_errors: true

    - name: ssh output
      debug: 
        msg: "{{ ssh.stdout }}"

    - name: 6.9 is compliant
      debug:
        msg: "6.9 is compliant"
      when: ssh.stdout == "PermitRootLogin no"
      register: compliant

    - name: Compliant
      debug:
        msg: "6.9 is compliant"
      when: compliant.msg == "6.9 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: Non-Compliant
      debug:
        msg: "6.9 is non-compliant"
      when: compliant.skipped == true
      ignore_errors: true
      register: isNonCompliant

    - name: Make it compliant
      shell: |
        awk '/^PermitRootLogin/ { $2 = "no" } { print }' /etc/ssh/sshd_config > /etc/ssh/sshd_config.CIS;
        mv /etc/ssh/sshd_config.CIS /etc/ssh/sshd_config;
        svcadm restart svc:/network/ssh;
      when: isNonCompliant.msg == "6.9 is non-compliant"
      ignore_errors: true

    - name: Rerun
      debug:
        msg: "Rerun script to view changes"
      when: isNonCompliant.msg == "6.9 is non-compliant"

    - name: FINAL
      debug:
        msg: "6.9 is compliant"
      when: isCompliant.msg == "6.9 is compliant"