- hosts: solaris
  become: true
  become_method: sudo
  vars:
    ansible_python_interpreter: /usr/local/python-3.6/bin/python3
    ansible_become_pass: '<your solaris machine password>'

  tasks:
    - name: '9.19 Check for Presence of User .netrc Files'
      shell: | 
        for dir in `logins -ox | awk -F: '($8 == "PS") { print $6 }'`; do 
        s -l ${dir}/.netrc 2>/dev/null 
        done
      register: audit1
      ignore_errors: true

    - name: audit1
      debug: 
        msg: "{{ audit1.stdout }}"

    - name: Compliant
      debug:
        msg: "9.19 is compliant"
      when: audit1.stdout == ""
      register: compliant
      ignore_errors: true

    - name: isCompliant
      debug:
        msg: "9.19 is compliant"
      when: compliant.msg == "9.19 is compliant"
      ignore_errors: true
      register: isCompliant

    - name: isNotCompliant
      debug:
        msg: | 
          Correct or justify any items discovered in the Audit step. Determine if any .netrc files exist, and work with the 
          owner to determine the best course of action in accordance with site policy. 
      when: compliant.skipped == true
      ignore_errors: true
      register: isNotCompliant

    - name: Final
      debug:
        msg: "9.19 is compliant"
      when: isCompliant.msg == "9.19 is compliant"